"""add_user_favorites

Revision ID: 0163e767d4a3
Revises: 391a30f6b803
Create Date: 2026-07-17 18:03:19.649776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0163e767d4a3'
down_revision: Union[str, Sequence[str], None] = '391a30f6b803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_favorites', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('user_favorites', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_favorites_id'), 'user_favorites', ['id'], unique=False)
    op.create_unique_constraint('uq_user_game_favorite', 'user_favorites', ['user_id', 'game_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_game_favorite', 'user_favorites', type_='unique')
    op.drop_index(op.f('ix_user_favorites_id'), table_name='user_favorites')
    op.drop_column('user_favorites', 'created_at')
    op.drop_column('user_favorites', 'id')
    # ### end Alembic commands ###
